### ISSUE TITLE
Url link in the `README` is not valid

### ISSUE THREAD

**Issue by popfido** [tensorchord/ai-infra-statistics#2]
It seems that the link url `https://ai-infra-statisticsgit-nuxwaw7accvhuheujqgwjk.streamlit.app/` in the README file cannot be accessed directly without authorization and looks more like a private link.

It takes me some time to find that the link `[ai-infra-statistics.streamlit.app/](https://ai-infra-statistics.streamlit.app/)` under project's `About` part is the true accessible one. LMFAO.

**Comment by gaocegege** [comment]
Thanks for the issue! Welcome PRs.
